<?php

/**
 * Implements hook_enable()
 */
function drupal_streamline_dev_enable() {
  // Redirect all outgoing mail to the local filesystem
  variable_set('mail_system', array('default-system' => 'DevelMailLog'));

  // Set local error reporting
  variable_set('error_level', ERROR_REPORTING_DISPLAY_ALL);
}

/**
 * Implements hook_disable()
 */
function drupal_streamline_dev_disable() {
  // Stop redirecting all outgoing mail
  variable_set('mail_system', array('default-system' => 'DefaultMailSystem'));
}
